### PR TITLE
Should we use production bucket and inventory?

### PR DESCRIPTION
**Pull request by peterdesmet**
I noticed some links refer to:

1. The `aloft` bucket, which will be removed. The `aloftdata` bucket should be used

2. The `aloft-inventory` bucket (with subfolder `aloft/aloft-hdf5-files-inventory/`). This bucket is on UAT. I wonder if the `inbo-aloft-prod-eu-west-1-inventory` bucket (with subfolder `/aloftdata/aloftdata-hdf5-files-inventory/`) should be used instead or if that will break tests.

### CODE REVIEW

**Review by stijnvanhoey — COMMENTED** [review]
Good point, I would propose:

- For the 'default' environmental variable when not provided (`os.environ.get("DESTINATION_BUCKET", "aloft")`) I would not use the prd version but the dev/uat bucket name and sns channels
- For the `s3_url_h5` I think it is ok to use the `aloftdata`  prd bucket name
- In the `Examples` sections of the docstrings I would sue the `aloftdata` prd name
- For the `tests/` files it should not matter as the S3-bucket is mocked for the tests. So you can choose whatever name you prefer but at the moment some tests did fail due to the name adjustments in the tests (you also adjust the `dummy_manifest.json` file)

**Comment by peterdesmet** [comment]
> For the 'default' environmental variable when not provided (`os.environ.get("DESTINATION_BUCKET", "aloft")`) I would not use the prd version but the dev/uat bucket name and sns channels

So that would then be `inbo-aloft-uat-eu-west-1-default`

> For the `s3_url_h5` I think it is ok to use the `aloftdata`  prd bucket name

Ok

> In the `Examples` sections of the docstrings I would sue the `aloftdata` prd name

Ok

> For the `tests/` files it should not matter as the S3-bucket is mocked for the tests. So you can choose whatever name you prefer but at the moment some tests did fail due to the name adjustments in the tests (you also adjust the `dummy_manifest.json` file, https://github.com/enram/vptstools/blob/main/tests/data/inventory/dummy_manifest.json#L9)

I will then use `aloftdata-mocked`

**Comment by peterdesmet** [comment]
Updated, but some tests are still failing, so I probably changed something I shouldn't have?

**Comment by stijnvanhoey** [comment]
> so I probably changed something I shouldn't have?

Main issue was that the default env vars were used in the end2end tests of the CLI commands instead of the dummy-aloftdata and dummy-inventory. I adjusted this and made sure other occurrences of the bucket name use the dummy-aloftdata naming.

**Pull request merged**
